### ISSUE TITLE
TestRunner: java.lang.AssertionError: Activity never becomes requested state "[CREATED, DESTROYED, RESUMED, STARTED]" (last lifecycle transition = "PRE_ON_CREATE")

### ISSUE THREAD

**Issue by Chaner2015** [allure-framework/allure-kotlin#47]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report

#### What is the current behavior?
在安卓机型上执行单元测试case，出现如下日志异常，和关联启动有关吗？是AndroidX test Runner的问题吗需要怎么处理

Started running tests
W/Settings: Setting always_finish_activities has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
E/TestRunner: failed: testCheckSelectable(com.example.albumdemo.albumAssetViewModel.CheckSelectableTest)
    ----- begin exception -----
E/TestRunner: java.lang.AssertionError: Activity never becomes requested state "[CREATED, DESTROYED, RESUMED, STARTED]" (last lifecycle transition = "PRE_ON_CREATE")
        at androidx.test.core.app.ActivityScenario.waitForActivityToBecomeAnyOf(ActivityScenario.java:338)
        at androidx.test.core.app.ActivityScenario.launchInternal(ActivityScenario.java:272)
        at androidx.test.core.app.ActivityScenario.launch(ActivityScenario.java:195)
        at androidx.test.ext.junit.rules.ActivityScenarioRule.lambda$new$0$ActivityScenarioRule(ActivityScenarioRule.java:70)
        at androidx.test.ext.junit.rules.ActivityScenarioRule$$Lambda$0.get(Unknown Source:2)
        at androidx.test.ext.junit.rules.ActivityScenarioRule.before(ActivityScenarioRule.java:103)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
        at io.qameta.allure.android.rules.LogcatRule$apply$1.evaluate(LogcatRule.kt:23)
        at io.qameta.allure.android.rules.ScreenshotRule$apply$1.evaluate(ScreenshotRule.kt:22)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at io.qameta.allure.kotlin.junit4.AllureRunner.run(Runners.kt:10)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
        at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2169)
    ----- end exception -----

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
【step1】  对testXXXcase()在安卓测试机上运行单元测试case
      执行命令行： adb shell am instrument -w -r    -e debug true -e class 'com.example.demo.Test#testXXXcase' com.demo.test/io.qameta.allure.android.runners.AllureAndroidJUnitRunner  (项目隐私问题把测试类名方法名等demo替换了)
     
【step2】测试设备中会安装test apk 、demo apk，并开始执行单元测试case ，但是出现了上述的异常日志

#### What is the expected behavior?
预期可以正常执行单元测试case，输出结果

#### Please tell us about your environment:
 vivo V1934A

    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    testImplementation 'androidx.test.ext:junit:1.1.1'
    //espresso
    androidTestImplementation 'androidx.test:runner:1.1.0'
    androidTestImplementation 'androidx.test:rules:1.1.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0'
    androidTestImplementation 'androidx.test.espresso:espresso-contrib:3.1.0'
    androidTestImplementation 'de.schroepf:android-xml-run-listener:0.4.0'

    androidTestImplementation "io.qameta.allure:allure-kotlin-model:2.1.2"
    androidTestImplementation "io.qameta.allure:allure-kotlin-commons:2.1.2"
    androidTestImplementation "io.qameta.allure:allure-kotlin-junit4:2.1.2"
    androidTestImplementation "io.qameta.allure:allure-kotlin-android:2.1.2"

| Allure version | 2.1.2 |
| --- | --- |
| Test framework | junit@4.12 |
| Allure integration | allure-kotlin-android@2.1.2 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc

**Comment by aljohnston112** [comment]
Can you run unit tests? If so, it might be related to this. 
https://github.com/android/android-test/issues/1377 
Check the logs for any exceptions that might be covered up by test framework

**Comment by aljohnston112** [comment]
Do you have ```debugImplementation 'androidx.test:core-ktx:1.4.0'```?
